# Numpy

## 1-it is a python library/package for mathematical computing and processing multi-dimensional array
## 2-it is written in c
## 3-it overcomes the problem of running slower algorithms on python by using multidimensional array
## 4-executes elementwise operation
## 5-performs linear alegbra ,fourier transform or any complex operation on it
## 6-core data structure of numpy is nd-array


### 1- normal python coding for dividing two parallel data

In [2]:
d=[400,300,100,200]
sp=[40,50,70,60]
m=list(zip(d,sp))
m

[(400, 40), (300, 50), (100, 70), (200, 60)]

In [6]:
main=[]
for i in m:
    l1=[]
    for j in i:
        l1.append(j)
    main.append(l1)
main
        
    

[[400, 40], [300, 50], [100, 70], [200, 60]]

In [9]:
time=[]
for k in main:
    time.append(k[0]/k[1])
print(time)
    

[10.0, 6.0, 1.4285714285714286, 3.3333333333333335]


### 2 - when we use numpy

In [1]:
import numpy as np
d1=np.array([400,300,100,200])
sp1=np.array([40,50,70,60])
d1/sp1

array([10.        ,  6.        ,  1.42857143,  3.33333333])

## Array

## 1 = stores homogenous data
## 2 = only in numbers
## 3 = fast and efficient
## 4 = operates only on homogenous data (only numbers)

# Creating array

In [14]:
a = np.array([1,2,3,4,5,6,7,8])
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [15]:
type(a)

numpy.ndarray

In [16]:
a.dtype

dtype('int32')

In [17]:
# 2d array creation
a2 = np.array([[1,3,7,9],[45,89,56,11]])
a2

array([[ 1,  3,  7,  9],
       [45, 89, 56, 11]])

In [22]:
# 3d array creation
s = np.array([[[1,2,3,4],[2,4,6,8]],[[20,45,56,90],[45,78,90,45]]])
s

array([[[ 1,  2,  3,  4],
        [ 2,  4,  6,  8]],

       [[20, 45, 56, 90],
        [45, 78, 90, 45]]])

In [19]:
# creating array from tuple
s = np.array((1,3,5,7,9))
s

array([1, 3, 5, 7, 9])

In [20]:
# creating array from string
s = np.array("hi hello why")
s
#it is a 0th.darray

array('hi hello why', dtype='<U12')

# Important properties \ attributes of Array:
## 1. ndim
## 2. shape
## 3. size
## 4. astype

In [23]:
# single dimensional array 
a = np.array([20,30,90])
print(a)

[20 30 90]


## property 1 of array - ndim

In [24]:
a.ndim

1

In [27]:
# 2d array
c = np.array([[1,2,3],[23,45,60]])
print(c)
print("")
print(c.ndim)

[[ 1  2  3]
 [23 45 60]]

2


In [28]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5]) # in  single dimension we can not judge the rows and columns
c = np.array([[1, 2, 3,45], [4, 5, 6,7],[3,5,6,7]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
e=np.array([[[[1, 2, 3], [4, 5, 6]]]])
f=np.array([[2,3,4,5]])
g=np.array([[[[[20,30]]]]])
print(a.ndim)
print(np.ndim(a))
print(b.ndim)
print(c.ndim)
print(d.ndim)
print(e.ndim)
print(f.ndim)
print(g.ndim)


0
0
1
2
3
4
2
5


In [2]:
import numpy as np
a1=np.array([1,2,3,4],ndmin=5)
a1

array([[[[[1, 2, 3, 4]]]]])

In [30]:
c = np.array([[1,2,3],[23,45,60]],ndmin=7)
c

array([[[[[[[ 1,  2,  3],
            [23, 45, 60]]]]]]])

## property of array 2 - shape

In [32]:
a1=np.array([1,2,3,4]) ## in 1d shape we cannot judge rows and columns
print(a1.shape)

(4,)


In [4]:
# determining of shape in 2d array
c = np.array([[1, 2, 3], [4, 5, 6]])
print(c.shape)
print(c)

(2, 3)
[[1 2 3]
 [4 5 6]]


In [3]:
c = np.array([[1, 2, 3,45], [4, 5, 6,7],[3,5,6,7]])
print(c.shape)
c

(3, 4)


array([[ 1,  2,  3, 45],
       [ 4,  5,  6,  7],
       [ 3,  5,  6,  7]])

In [35]:
c = np.array([[1, 2, 3]])
c.shape

(1, 3)

In [4]:
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(d.shape)
d

(2, 2, 3)


array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [38]:
k=np.array([[[[[[[2,3,4],[45,78,90],[50,90,89]]]]]]])
print(k.shape)
print(k)


(1, 1, 1, 1, 1, 3, 3)
[[[[[[[ 2  3  4]
      [45 78 90]
      [50 90 89]]]]]]]


In [39]:
a=np.array([[[[[[[["pizza","sweet corn","coffee","lemonade"]]]]]]]])
a.shape


(1, 1, 1, 1, 1, 1, 1, 4)

In [2]:
import numpy as np
k = np.array([[[2,3],[2,3],[2,3],[2,3]],[[2,3],[2,3],[2,3],[2,3]]])
k.shape

(2, 4, 2)

In [9]:
#create a shape odf array 1,1,3,3
j = np.array([[[[2,3,4],[3,5,6],[6,7,8]]]])
print(j)
print(j.shape)

[[[[2 3 4]
   [3 5 6]
   [6 7 8]]]]
(1, 1, 3, 3)


In [12]:
#1,1,3,3,3
k = np.array([[[[[2,3,4],[2,3,4],[2,3,4]],[[2,3,4],[2,3,4],[2,3,4]],[[2,3,4],[2,3,4],[2,3,4]]]]])
print(k.shape)
print(k)
print(np.sort(k))

(1, 1, 3, 3, 3)
[[[[[2 3 4]
    [2 3 4]
    [2 3 4]]

   [[2 3 4]
    [2 3 4]
    [2 3 4]]

   [[2 3 4]
    [2 3 4]
    [2 3 4]]]]]
[[[[[2 3 4]
    [2 3 4]
    [2 3 4]]

   [[2 3 4]
    [2 3 4]
    [2 3 4]]

   [[2 3 4]
    [2 3 4]
    [2 3 4]]]]]


## rank is the same as number of dimension

In [14]:
d = np.array([20,40,70,90])
print(np.size(d))
print(np.size(d,axis=0))

4
4


In [18]:
a = np.array([[1,2,3,4],[4,5,6,7]])
print(np.size(a))
print(np.size(a,0))
print(np.size(a,1))

8
2
4


In [24]:
# 3d Array
a = np.array([[[1,2,3,4],[4,5,6,7]],[[1,2,3,4],[2,5,3,4]]])
print(np.size(a))
print(np.size(a,0))
print(np.size(a,1))
print(np.size(a,2))


16
2
2
4


## item size it specifies how much memory does one element is alloted - always shows in bits 

In [26]:
# item size it always shows in bits
print(a.size*a.itemsize)

64


### dtype always in default is float


In [8]:
a=np.ones((2,3))
print(a)
print(a.dtype)

[[1. 1. 1.]
 [1. 1. 1.]]
float64


In [9]:
# create an array of shape 2,3,1
a=np.zeros((2,3,1))
a

array([[[0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.]]])

## astype - conversion of one datatype to another

In [35]:
a1=a.astype("int")
print(a1)
print(a1.dtype)

[[[1]
  [1]
  [1]]

 [[1]
  [1]
  [1]]]
int32


## arrays are faster then list datatype (coding is short in arrays)
## arrays can perform element wise operation while list cannot
## arrays take less memory

In [36]:

import sys
l=list(range(100))
a=np.arange(100)
print(sys.getsizeof(l))
print(a.itemsize)
print("list takes :",sys.getsizeof(l)*len(l),"bytes")  ##ys.getsizeof(l) : size of each element in the list
print("array takes : ",a.itemsize*a.size,"bytes" ) ## itemsize: size of each element in the array.


856
4
list takes : 85600 bytes
array takes :  400 bytes


# Array Indexing : in 1D

In [17]:
a = np.array([1,2,3,4])
print(a[0])
print(a[2:])
print(a[1:3:1])

1
[3 4]
[2 3]


## Array Indexing : In 2D

In [53]:
a=np.array([[2,3,4,5,6],[7,8,9,0,90],[20,30,40,50,90]])
print(a[0])

print(a[-1])

print(a[-1][2])

print(a[-1][3:])

print(a[:,1])

print(a[:,1:5:3])

print(a[0:3:2,0:4:3])
print(a)

[2 3 4 5 6]
[20 30 40 50 90]
40
[50 90]
[ 3  8 30]
[[ 3  6]
 [ 8 90]
 [30 90]]
[[ 2  5]
 [20 50]]
[[ 2  3  4  5  6]
 [ 7  8  9  0 90]
 [20 30 40 50 90]]


In [52]:
print(a[0:3:2])

[[ 2  3  4  5  6]
 [20 30 40 50 90]]


In [56]:
a

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9,  0, 90],
       [20, 30, 40, 50, 90]])

In [55]:
a[1:3,1:3]

array([[ 8,  9],
       [30, 40]])

In [57]:
a=np.array([[2,3,4,5,6],[7,8,9,0,90],[20,30,40,50,90]])  # 2d array  here , 
print(a)
print(a[0]) #or print(a[-3]) means first row
print(a[1]) #or print(a[-2]) means second row
print(a[2]) #or print(a[-1]) means third row
print(a[-1]) # or print(a[2])  means  last row
print(a[0][2]) # fetch 4
print(a[1][2:]) # 9,0,90
print(a[-2][0])  # fetch 7
print(a[:,2])  ## all rows with 2nd column  (discontinous manner)
print(a[0:2,2:]) ## ist and 2nd rows with columns from 2nd(disconinous manner)
print(a[1,2:3])
print(a[0:3:2,2:5:2]) ## feth 4,6 40 ,90
#print(a[[0,2],[1,3]])
print(a[0:3:2,1:4:2]) ## fetch 3, 30 5 and 50
 


[[ 2  3  4  5  6]
 [ 7  8  9  0 90]
 [20 30 40 50 90]]
[2 3 4 5 6]
[ 7  8  9  0 90]
[20 30 40 50 90]
[20 30 40 50 90]
4
[ 9  0 90]
7
[ 4  9 40]
[[ 4  5  6]
 [ 9  0 90]]
[9]
[[ 4  6]
 [40 90]]
[[ 3  5]
 [30 50]]


In [66]:
a=np.array([[[[[[[["pizza","sweet corn","coffee","lemonade"]]]]]]]])
a


array([[[[[[[['pizza', 'sweet corn', 'coffee', 'lemonade']]]]]]]],
      dtype='<U10')

In [60]:
print(a[0][0][0][0][0][0][0])

['pizza' 'sweet corn' 'coffee' 'lemonade']


In [69]:
print(a[0][0][0][0][0][0][0][1:])

['sweet corn' 'coffee' 'lemonade']


In [70]:
a=np.array([[[[[1,2,3,50,],[4,5,6,90],[7,8,9,99],[11,12,3,98]]]]])
a

array([[[[[ 1,  2,  3, 50],
          [ 4,  5,  6, 90],
          [ 7,  8,  9, 99],
          [11, 12,  3, 98]]]]])

In [71]:
a[0][0][0][-1][-1]

98

In [72]:
a[0][0][0][3][-1]


98

In [73]:
a=np.array([[[[1,2,3,4,5],[6,7,8,9,0],[11,12,13,14,15],[16,17,18,19,20]]]])
a

array([[[[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9,  0],
         [11, 12, 13, 14, 15],
         [16, 17, 18, 19, 20]]]])

In [74]:
a[0][0][-1][-2]

19

In [76]:
a[0][0][2][2:5:2]

array([13, 15])

In [2]:
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [3]:
arr[1][0]

array([7, 8, 9])

In [10]:
arr[1][:,1:] # 8,9,11,12 or # 11,12

array([[ 8,  9],
       [11, 12]])

## Indexing With Boolean (Important From EDA Point OF View)

In [11]:
a=np.array([[20,30,60],[40,80,90],[70,90,100]])
a


array([[ 20,  30,  60],
       [ 40,  80,  90],
       [ 70,  90, 100]])

In [12]:
a<40

array([[ True,  True, False],
       [False, False, False],
       [False, False, False]])

In [14]:
z=a<40
z

array([[ True,  True, False],
       [False, False, False],
       [False, False, False]])

In [16]:
print(a[z])
# or 
print(a[a<40])

[20 30]
[20 30]


In [17]:
## np.where returns index
[np.where(a<40,85,"Nothing")]

[array([['85', '85', 'Nothing'],
        ['Nothing', 'Nothing', 'Nothing'],
        ['Nothing', 'Nothing', 'Nothing']], dtype='<U11')]

In [22]:
## greater than 40 and also even
print(a[(a%2==0)&(a>40)])


[ 60  80  90  70  90 100]


In [23]:
a=[[[[2,3,4,5],[40,50,60,90]]]]
a

[[[[2, 3, 4, 5], [40, 50, 60, 90]]]]

In [65]:
m=np.array(a)
m
print(m[0][0][:,1])
print(m[0][0][1,2:])
print(m[0][0][[0,1],[1,3]])


[ 3 50]
[60 90]
[ 3 90]


In [90]:
m[0][0][:,2]

array([ 4, 60])

# How TO fetch Each Element Of Array Using Loop In Order to perform Any # 
# Logic On Each Element : Using np.nditer


In [94]:
a = np.array([[2,3,4],[5,6,7]])
print(a)
for i in np.nditer(a):
    print(i)

[[2 3 4]
 [5 6 7]]
2
3
4
5
6
7


## Copy and View

In [95]:
##   copy
a = np.array([1,2,3,4])
a1=a.copy() # Deep Copy
a1[3]=70
print("copy...",a1)
print("Original Array..",a)

copy... [ 1  2  3 70]
Original Array.. [1 2 3 4]


In [96]:
#  VIew
a = np.array([1,2,3,4])
a1=a.view() # Deep Copy
a1[3]=70
print("copy...",a1)
print("Original Array..",a)

copy... [ 1  2  3 70]
Original Array.. [ 1  2  3 70]


In [97]:
## Another Example Of View Copy
a2=a1 #
a2[2]=200
print("original..",a1)
print("View Copy..",a2)


original.. [  1   2 200  70]
View Copy.. [  1   2 200  70]


## Shape Manipulation : Reshape , Resize (Shallow=Reshape,DeepCopy=Resize