## Arithmetic Operations on Arrays

In [2]:
import numpy as np

In [3]:
a1=np.array([[1,2,3,4],[3,4,5,6],[7,8,9,3]])
a1

a2=np.array([[3,20,5,4],[3,4,50,6],[7,8,7,9]])
a2

array([[ 3, 20,  5,  4],
       [ 3,  4, 50,  6],
       [ 7,  8,  7,  9]])

In [4]:
a1+a2

array([[ 4, 22,  8,  8],
       [ 6,  8, 55, 12],
       [14, 16, 16, 12]])

In [5]:
a1-a2

array([[ -2, -18,  -2,   0],
       [  0,   0, -45,   0],
       [  0,   0,   2,  -6]])

In [6]:
a1*a2

array([[  3,  40,  15,  16],
       [  9,  16, 250,  36],
       [ 49,  64,  63,  27]])

In [7]:
a1/a2

array([[0.33333333, 0.1       , 0.6       , 1.        ],
       [1.        , 1.        , 0.1       , 1.        ],
       [1.        , 1.        , 1.28571429, 0.33333333]])

In [8]:
a1%a2

array([[1, 2, 3, 0],
       [0, 0, 5, 0],
       [0, 0, 2, 3]], dtype=int32)

In [9]:
a1//a2

array([[0, 0, 0, 1],
       [1, 1, 0, 1],
       [1, 1, 1, 0]], dtype=int32)

In [10]:
a1<a2

array([[ True,  True,  True, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [11]:
a1>2

array([[False, False,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [12]:
a1 = [[4,9,16,36]]
a1

[[4, 9, 16, 36]]

In [13]:
np.sqrt(a1)


array([[2., 3., 4., 6.]])

In [14]:
np.sin(a1)

array([[-0.7568025 ,  0.41211849, -0.28790332, -0.99177885]])

In [15]:
import math
a = 2.3
math.floor(a)

2

In [16]:
a = -3.4
math.ceil(a)

-3

In [17]:
round(23.56789)

24

In [18]:
np.ceil(a1)

array([[ 4.,  9., 16., 36.]])

In [19]:
np.floor(a1)

array([[ 4.,  9., 16., 36.]])

In [20]:
a1= np.array([20.4,-2.6,3.9])
np.ceil(a1)

array([21., -2.,  4.])

In [21]:
np.floor(a1)

array([20., -3.,  3.])

In [22]:
np.min(a1)

-2.6

In [23]:
a1=np.array([[1,2,3,4],[3,4,5,6],[7,8,9,0]])
a1

array([[1, 2, 3, 4],
       [3, 4, 5, 6],
       [7, 8, 9, 0]])

In [24]:
np.argmax(a1)

10

In [25]:
np.max(a1)

9

In [26]:
a1.max(axis=0)

array([7, 8, 9, 6])

In [27]:
a1.max(axis=1)

array([4, 6, 9])

In [28]:
a2.max()

50

In [29]:
a1.sum(axis=0)

array([11, 14, 17, 10])

In [30]:
a1.sum(axis=1)

array([10, 18, 24])

In [31]:
np.sort(a1)

array([[1, 2, 3, 4],
       [3, 4, 5, 6],
       [0, 7, 8, 9]])

In [33]:
np.sort(a1,axis=0)

array([[1, 2, 3, 0],
       [3, 4, 5, 4],
       [7, 8, 9, 6]])

In [34]:
np.sort(a1,axis=1)

array([[1, 2, 3, 4],
       [3, 4, 5, 6],
       [0, 7, 8, 9]])

### MATRIX

In [36]:
a=np.mat([[1,2],[3,4]])
a

matrix([[1, 2],
        [3, 4]])

In [37]:
a= np.mat([[1,2,3],[4,5,6],[7,8,9]])
a

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

## - Difference between Matrix and Array
## - matrix atmost is 2(dimensional) and Arrays Are N(dimensional)

In [38]:
a= np.mat([[[1,2,3],[4,5,6],[7,8,9]]])
a  ## ValueError("matrix must be 2-dimensional")

ValueError: matrix must be 2-dimensional

## Difference of matrix and Array Product

In [39]:
m1=np.array([[1,2],[3,4]])
m2=np.array([[3,4],[8,9]])
m1*m2 

array([[ 3,  8],
       [24, 36]])

In [40]:
m1=np.mat([[1,2],[3,4]])
m2=np.mat([[3,4],[8,9]])
m1*m2 

matrix([[19, 22],
        [41, 48]])

In [48]:
m1=np.mat([[1,2],[3,4]])  ## Transpose- two ways of transposing by using .T or np.transpose
print(m1.T)
print(m1)

[[1 3]
 [2 4]]
[[1 2]
 [3 4]]


In [46]:
m1.transpose()

matrix([[1, 3],
        [2, 4]])

## Trace

In [51]:
m2.trace()

matrix([[12]])

## inverse

In [52]:
a=np.array([[1,2],[3,4]])  
d=np.matrix([[1,2],[3,4]])
print(a.shape)
print(d.shape)
np.linalg.inv(d)

(2, 2)
(2, 2)


matrix([[-2. ,  1. ],
        [ 1.5, -0.5]])

## Broadcasting

In [55]:
# case 1 When Shape Is Same
a = np.arange(8).reshape(2,4)
a1 = np.arange(8).reshape(2,4)
print(a+a1)

# Case 2 When Shape Is Different 
a1=np.arange(9).reshape(3,3)
print(a1*4) ## Effect of Broadcast


[[ 0  2  4  6]
 [ 8 10 12 14]]
[[ 0  4  8]
 [12 16 20]
 [24 28 32]]


In [56]:
# Case 2.2 When shape is different
## Conditions Must Be met For  Broadcasting Which Is - One Of The Dimension Is Of Size 1 or It Will raise Error
a2= np.arange(12).reshape(4,3)
print(a2)
print(a1)
print(a1+a2)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


ValueError: operands could not be broadcast together with shapes (3,3) (4,3) 

## How To Generate Random Values in Arrays Or in Python Numpy 
## to generate a fixed random value we use seed

In [57]:
import numpy as np
a=np.random.random()
a

0.9151127676422295

In [66]:
a=np.random.seed(4)
a=np.random.random()
a

0.9670298390136767

## Generating single random value with a given range

In [70]:
np.random.uniform(1,10)

9.850606094577815

## Generating single random value with a given range

In [71]:
np.random.uniform(1,100,10)

array([17.2203819 , 60.13606045,  1.88962367, 39.27055698,  5.37184574,
       95.7086438 , 44.17851804, 94.94875337, 78.84429261, 86.76264056])

## Generate Random Values of Certain Dimensions

In [74]:
np.random.uniform(1,100,10).reshape(5,2)

array([[38.18200109, 50.75077287],
       [68.98004091, 26.11428522],
       [55.91934543, 62.86815356],
       [89.65461544, 36.92250525],
       [64.11815023, 19.95319381]])

## To Generate Random Numbers In Integer We Use randint

In [82]:
a=np.random.randint(10,100,10)
a

array([84, 30, 90, 17, 61, 20, 51, 96, 25, 51])

In [83]:
a=np.random.normal(loc=10,scale=4,size=1000)
a

array([ 5.69883964, 18.08962027,  7.74049881,  3.8282838 , 13.48336712,
        9.29915789, 10.19441203, 10.75458481, 10.83725395,  8.50222033,
       13.81879439, 12.09299065,  8.01672592,  9.31414156,  6.2225256 ,
       11.1234587 , 12.95298845, 12.60301292, 12.45896252,  9.49372562,
       16.31549699,  9.17127329, 10.12026833,  8.65528064, 10.32505508,
        9.03790329, 18.1287173 , 11.70338685,  3.26814044,  8.26445448,
        4.33508988, 13.51959598, 15.49837293,  8.19582836, 12.45413051,
        9.15937375, 11.63223266, 16.92959402,  8.60220817,  5.06745271,
       12.87309756, 12.06623853, 12.69520597, 14.10581988,  7.27540628,
        2.13594112, 14.16362547,  8.36539875,  5.17039816,  5.32683887,
       14.51349333, 10.72333325, 11.21160814, 13.40154748,  7.29239622,
        5.49954164,  6.58819488,  5.58170154,  8.83561681,  6.43609707,
       10.15454085,  8.07660343,  9.68008204, 12.59916134, 15.60510758,
       16.22375166, 10.45968872, 10.84948115,  7.96647909, 14.02

In [84]:
import statistics
print(statistics.mode(a))
print(np.mean(a),np.median(a))

5.69883963878505
10.150139469636924 10.03295675765553


In [85]:
#Identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [87]:
#Identity matrix
np.eye(3,k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [88]:
np.eye(3,k=-1)

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [89]:
a=np.array([[1,2,3],[4,5,6],[10,20,30]])
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 20, 30]])

In [90]:
print("diagonal elements are :",np.diag(a,k=1))

diagonal elements are : [2 6]


In [91]:
print("diagonal elements are :",np.diag(a,k=0))

diagonal elements are : [ 1  5 30]


In [92]:
print("diagonal elements are :",np.diag(a,k=-1))

diagonal elements are : [ 4 20]


## Diagflat : for creating Diagonal array directly based on the Value of k

In [93]:
a1=np.diagflat([1,2,3,4,5],k=0)
a1

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [94]:
## if k is 1 or -1
a1=np.diagflat([1,2,3,4,5],k=1)
a1

array([[0, 1, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0],
       [0, 0, 0, 3, 0, 0],
       [0, 0, 0, 0, 4, 0],
       [0, 0, 0, 0, 0, 5],
       [0, 0, 0, 0, 0, 0]])

In [95]:
a1=np.diagflat([1,2,3,4,5],k=-1)
a1

array([[0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 5, 0]])

## From Function

In [96]:
print(np.fromfunction(lambda i,j:i*j,(4,4)))

[[0. 0. 0. 0.]
 [0. 1. 2. 3.]
 [0. 2. 4. 6.]
 [0. 3. 6. 9.]]


In [98]:
print(np.fromfunction(lambda i,j:i+j,(4,4)))
print()
print(np.fromfunction(lambda i,j:i-j,(4,4)))

print(np.fromfunction(lambda i,j:i**j,(4,4)))


[[0. 1. 2. 3.]
 [1. 2. 3. 4.]
 [2. 3. 4. 5.]
 [3. 4. 5. 6.]]
[[ 0. -1. -2. -3.]
 [ 1.  0. -1. -2.]
 [ 2.  1.  0. -1.]
 [ 3.  2.  1.  0.]]
[[ 1.  0.  0.  0.]
 [ 1.  1.  1.  1.]
 [ 1.  2.  4.  8.]
 [ 1.  3.  9. 27.]]
