In [1]:
import numpy as np

## Array Indexing In 1-Dimension

In [2]:
a = np.array([1,2,3,4])
print(a[0])
print(a[2:])
print(a[1:3:1])

1
[3 4]
[2 3]


## Array Indexing In 2-Dimension

In [3]:
a=np.array([[2,3,4,5,6],[7,8,9,0,90],[20,30,40,50,90]])
print(a[0])

print(a[-1])

print(a[-1][2])

print(a[-1][3:])

print(a[:,1])

print(a[:,1:5:3])

print(a[0:3:2,0:4:3])
print(a)

[2 3 4 5 6]
[20 30 40 50 90]
40
[50 90]
[ 3  8 30]
[[ 3  6]
 [ 8 90]
 [30 90]]
[[ 2  5]
 [20 50]]
[[ 2  3  4  5  6]
 [ 7  8  9  0 90]
 [20 30 40 50 90]]


In [4]:
print(a[0:3:2])

[[ 2  3  4  5  6]
 [20 30 40 50 90]]


In [5]:
a[1:3,1:3]

array([[ 8,  9],
       [30, 40]])

In [6]:
a=np.array([[2,3,4,5,6],[7,8,9,0,90],[20,30,40,50,90]])  # 2d array  here , 
print(a)
print(a[0]) #or print(a[-3]) means first row
print(a[1]) #or print(a[-2]) means second row
print(a[2]) #or print(a[-1]) means third row
print(a[-1]) # or print(a[2])  means  last row
print(a[0][2]) # fetch 4
print(a[1][2:]) # 9,0,90
print(a[-2][0])  # fetch 7
print(a[:,2])  ## all rows with 2nd column  (discontinous manner)
print(a[0:2,2:]) ## ist and 2nd rows with columns from 2nd(disconinous manner)
print(a[1,2:3])
print(a[0:3:2,2:5:2]) ## feth 4,6 40 ,90
#print(a[[0,2],[1,3]])
print(a[0:3:2,1:4:2]) ## fetch 3, 30 5 and 50
 

[[ 2  3  4  5  6]
 [ 7  8  9  0 90]
 [20 30 40 50 90]]
[2 3 4 5 6]
[ 7  8  9  0 90]
[20 30 40 50 90]
[20 30 40 50 90]
4
[ 9  0 90]
7
[ 4  9 40]
[[ 4  5  6]
 [ 9  0 90]]
[9]
[[ 4  6]
 [40 90]]
[[ 3  5]
 [30 50]]


In [7]:
a=np.array([[[[[[[["pizza","sweet corn","coffee","lemonade"]]]]]]]])
a

array([[[[[[[['pizza', 'sweet corn', 'coffee', 'lemonade']]]]]]]],
      dtype='<U10')

In [8]:
print(a[0][0][0][0][0][0][0])

['pizza' 'sweet corn' 'coffee' 'lemonade']


In [9]:
a=np.array([[[[[1,2,3,50,],[4,5,6,90],[7,8,9,99],[11,12,3,98]]]]])
a

array([[[[[ 1,  2,  3, 50],
          [ 4,  5,  6, 90],
          [ 7,  8,  9, 99],
          [11, 12,  3, 98]]]]])

In [10]:
a[0][0][0][-1][-1]

98

In [13]:
a=np.array([[[[1,2,3,4,5],[6,7,8,9,0],[11,12,13,14,15],[16,17,18,19,20]]]])
a

array([[[[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9,  0],
         [11, 12, 13, 14, 15],
         [16, 17, 18, 19, 20]]]])

In [12]:
a[0][0][-1][-2]

19

In [14]:
a[0][0][2][2:5:2]

array([13, 15])

In [15]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [16]:
arr[1][0]

array([7, 8, 9])

In [17]:
arr[1][:,1:] # 8,9,11,12 or # 11,12

array([[ 8,  9],
       [11, 12]])

## Indexing With Boolean (Important From EDA Point OF View)

In [19]:
a=np.array([[20,30,60],[40,80,90],[70,90,100]])
a

array([[ 20,  30,  60],
       [ 40,  80,  90],
       [ 70,  90, 100]])

In [20]:
z=a<40
z

array([[ True,  True, False],
       [False, False, False],
       [False, False, False]])

In [21]:
a[z]

array([20, 30])

## np.where returns index

In [23]:
[np.where(a<40,85,"Nothing")]

[array([['85', '85', 'Nothing'],
        ['Nothing', 'Nothing', 'Nothing'],
        ['Nothing', 'Nothing', 'Nothing']], dtype='<U11')]

In [24]:
## greater than 40 and also even
print(a[(a%2==0)&(a>40)])

[ 60  80  90  70  90 100]


In [26]:
a=[[[[2,3,4,5],[40,50,60,90]]]]
a
m=np.array(a)
m
print(m[0][0][:,1])
print(m[0][0][1,2:])
print(m[0][0][[0,1],[1,3]])

[ 3 50]
[60 90]
[ 3 90]


In [27]:
m[0][0][:,2]

array([ 4, 60])