In [1]:
import numpy as np

In [3]:
x = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
x.shape

(2, 6)

### RESHAPE

In [4]:
# RESHAPE
x = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
x1=x.reshape(1,12)
print("shallow copy..",x1)
print("original array..",x)
x2=x.reshape(3,4)
print("Copy 2..",x2)
x3=x.reshape(6,2)
print("Copy 3..",x3)

shallow copy.. [[ 1  2  3  4  5  6  7  8  9 10 11 12]]
original array.. [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
Copy 2.. [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Copy 3.. [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


### Resize

In [ ]:
x1=x.resize(1,12)
print("deep copy..",x1) ## Returns Nothing ... Changes Original Data
print("original array..",x)

In [5]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr= arr.reshape(2,2,-1)
newarr1= arr.reshape(-1,2,2)
print(newarr)
print(newarr1)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Flatten The Array - Ravel (Shallow Copy),Flatten(Deepcopy)
### Flattening The Arrays means Converting Multi-dimensional Arrays Into 1D Arrays..

In [6]:
# By USing Ravel

arr = np.array([[1,2,3],[4,5,7]])
arr1 = arr.ravel()
print("1d ..",arr1)
print("2d ..",arr)

1d .. [1 2 3 4 5 7]
2d .. [[1 2 3]
 [4 5 7]]


In [7]:
arr1[2]=360
print(arr,"Original")
print(arr1,"Deep Copy")

[[  1   2 360]
 [  4   5   7]] Original
[  1   2 360   4   5   7] Deep Copy


In [8]:
# By Using Flatten

arr = np.array([[1,2,3],[4,5,7]])
arr1 = arr.flatten()
print("1d ..",arr1,"Copy")
print("2d ..",arr,"original")
arr1[2]=360
print(arr,"Original")
print(arr1,"shallow Copy")

1d .. [1 2 3 4 5 7] Copy
2d .. [[1 2 3]
 [4 5 7]] original
[[1 2 3]
 [4 5 7]] Original
[  1   2 360   4   5   7] shallow Copy


In [9]:
# BY Using Reshape -1

arr = np.array([[1,2,3],[4,5,7]])
arr1 = arr.reshape(-1)
print("1d ..",arr1,"Copy")
print("2d ..",arr,"original")
arr1[2]=360
print(arr,"Original")
print(arr1,"Deep Copy")

1d .. [1 2 3 4 5 7] Copy
2d .. [[1 2 3]
 [4 5 7]] original
[[  1   2 360]
 [  4   5   7]] Original
[  1   2 360   4   5   7] Deep Copy


# Arange - Returns an Arrays Of Consecutive Generated Numbers


In [10]:
a=np.arange(1,11)
print(a)
a1=np.arange(1,11,2)
print(a1)
a2=np.arange(1.1,11.2,0.2)
print(a2)

[ 1  2  3  4  5  6  7  8  9 10]
[1 3 5 7 9]
[ 1.1  1.3  1.5  1.7  1.9  2.1  2.3  2.5  2.7  2.9  3.1  3.3  3.5  3.7
  3.9  4.1  4.3  4.5  4.7  4.9  5.1  5.3  5.5  5.7  5.9  6.1  6.3  6.5
  6.7  6.9  7.1  7.3  7.5  7.7  7.9  8.1  8.3  8.5  8.7  8.9  9.1  9.3
  9.5  9.7  9.9 10.1 10.3 10.5 10.7 10.9 11.1]


## Line Space 

In [12]:
a=np.linspace(-30,30,10) # 10 elemnts Generated 
# linspace() creates an array of equally spaced 10 elements
a

array([-30.        , -23.33333333, -16.66666667, -10.        ,
        -3.33333333,   3.33333333,  10.        ,  16.66666667,
        23.33333333,  30.        ])

In [13]:
a=np.arange(-30,30,10) # 10 elemnts not Generated
a

array([-30, -20, -10,   0,  10,  20])

## Log Space - Generates log value of linspace 

In [14]:
a=np.logspace(-30,30,10) # Show Log Value of Linspace
a

array([1.00000000e-30, 4.64158883e-24, 2.15443469e-17, 1.00000000e-10,
       4.64158883e-04, 2.15443469e+03, 1.00000000e+10, 4.64158883e+16,
       2.15443469e+23, 1.00000000e+30])

In [16]:
a=np.array([[[[2,3,4,5],[40,50,60,90]]]])
a

array([[[[ 2,  3,  4,  5],
         [40, 50, 60, 90]]]])

In [17]:
print(a[0][0][[0,1],[1,3]])

[ 3 90]


In [18]:
a=np.arange(3,30,2) #,,13 15 21 29
print(a)
print(a[[5,6,9,13]])

[ 3  5  7  9 11 13 15 17 19 21 23 25 27 29]
[13 15 21 29]


# some arrays are used for initialization purpose
## 1 np.ones()
## 2 np.zeros()
## 3 np.empty()

In [19]:
a = np.empty([1,4,4])
print(a)

[[[1.39838196e-76 1.39804329e-76 1.39804329e-76 1.39804329e-76]
  [1.39804329e-76 1.39804329e-76 1.39804329e-76 9.73041592e-72]
  [9.73041595e-72 9.73041595e-72 9.73041595e-72 9.73041595e-72]
  [1.39804329e-76 1.39804329e-76 1.39804329e-76 9.73041595e-72]]]


In [20]:
a = np.empty([1,3],dtype="int")
a

array([[912451088,       564,         0]])

In [21]:
a=np.zeros([3,4],dtype="int")
a

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [24]:
a=np.ones([5,4],dtype="int")
a

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])